Repository chingu-voyages/v8-geckos-team-04, pull requests merged in 2019-03, with the labels that each got.

#14 Feature/admin get language youtube videos
  .gitignore
  src/__tests__/Admin.test.js
  src/components/Admin.js
Labels: enhancement

#16 Feature/admin write youtube data to files
  public/index.html
  src/api/DatabaseFileBased.js
  src/api/DatabasePhoenixBased.js
  src/components/Admin.js
Labels: enhancement

#22 Refactor/extract title operations to own function
  src/api/Helpers.js
  src/components/Admin.js
Labels: refactor

#24 Include Bootstrap 4 in Admin.js for table styles. - Pull request #1 of 3
  src/bootstrap.min.css
  src/components/Admin.js
Labels: refactor

#27 Re-isolate bootstrap to Admin.js only.
  src/bootstrap.min.css
  src/components/Admin.js
Labels: bug

#33 Refactor/load youtube videos on admin page load
  src/api/Helpers.js
  src/api/Languages.js
  src/components/Admin.js
  src/components/AdminOneVideoForm.js
  src/components/App.js
  src/components/Video.js
  src/index.js
Labels: enhancement, refactor

#34 Feature/get 3 random videos function
  src/api/Languages.js
  src/components/Video.js
Labels: enhancement, refactor

#35 Bug/videos were showing that werent languages
  src/api/Helpers.js
  src/api/Languages.js
  src/components/Video.js
Labels: bug

#36 Feature/history localstorage
  guess_the_language/assets/package-lock.json
  src/components/History.js
  src/components/Video.js
  src/index.js
Labels: enhancement

#38 Bug/sometimes duplicates out of 3 chosen videos
  src/api/Languages.js
  src/components/Game.js
  src/components/History.js
  src/components/Main.js
  src/components/Score.js
  src/components/Video.js
Labels: bug
