Repository chingu-voyages/v8-geckos-team-04, pull requests merged in 2019-04, with the labels that each got.

#41 Refactor/random initial video instead of hardcoded
  src/components/Video.js
Labels: refactor

#46 Refactor/use localstorage for languages global
  .gitignore
  src/api/Languages.js
  src/components/Admin.js
  src/components/App.js
  src/components/Game.js
  src/components/Video.js
Labels: enhancement, refactor

#47 UseEffect in Video component tells handleNext to reset global qnum if starting a new game.
  src/components/Game.js
  src/components/Score.js
  src/components/Video.js
Labels: bug, refactor

#55 Bug/get random choice from videos with same language
  src/components/Video.js
Labels: bug

#56 Refactor/admin can sort table by fields
  README.md
  public/css/styles.css
  src/api/Helpers.js
  src/api/Languages.js
  src/components/Admin.js
Labels: enhancement

#59 Fix Error: Invariant failed: You should not use <Switch> outside a <R…
  package-lock.json
  src/components/App.js
  src/index.js
Labels: bug
